services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backendnew
    ports:
      - "5000:5000"
    env_file:
      - ./backendnew/.env
    depends_on:
      - mongodb
    volumes:
      - ./backendnew:/app
      - /app/node_modules

volumes:
  mongo-data: {}
